improve performance, make code cleaner, fix logic problems and lint code.
dskvr/nostr-watch pull request #454
Opened 2023-02-25 20:54 UTC by horberlan

2023-02-27 13:26 UTC, dskvr commented
Thanks! A lot of this looks good, some changes need to be reverted. I'll do full review soon.

2023-02-27 13:28 UTC, dskvr requested changes
There are a number of regressions in this PR that will cause many issues in future releases.

2023-02-27 13:28 UTC, dskvr commented on src/utils/index.js
> +        pool.close()
This doesn't do anything.

2023-02-27 13:28 UTC, dskvr commented on src/components/relays/jobs/RelayCanonicalsJob.vue
> +  name: 'CanoniCals',
this should be Canonicals

2023-02-27 13:28 UTC, dskvr commented on scripts/geo.js
> +  let geo;
This file is no longer an essential script, it was used during early days to create geo-data during pre-build instead of at runtime.

2023-02-27 13:28 UTC, dskvr commented on src/components/relays/jobs/CheckP2R.vue
> +  async checkP2R(force) {
this is a regression, you have removed it from the job-queue. It needs to be in the job queue.

2023-02-27 13:31 UTC, dskvr commented
I haven't found anything that improves performance yet. Can you please elaborate on your changes?

2023-02-28 18:14 UTC, horberlan commented
@dskvr Can you review the changes?

2023-03-01 08:31 UTC, dskvr requested changes
There are still regressions in this branch.

2023-03-11 16:53 UTC, dskvr commented
Closing this since it's gone inactive and the build was failing after changes. Very open to many of your changes, but they need to take into consideration the Roadmap and existing functionality. If you're still interested in pushing some improvements, please write a concise issue and then submit a PR that addresses only that issue.

2023-03-11 16:53 UTC, closed without merging